### PR TITLE
Issue#10: PKGBUILD: changed the source file name for installation of …

### PR DESCRIPTION
**Pull request by CompileMyLife**
…macfand.service from macfand.service to macfand.service.gen

When installing through yay, exit code 4 occurs as seen in the below log. Issue #10 speaks of this.
macfand-git_ERROR

To test it apply:
```console
$ make
$ make install
```

### CODE REVIEW

**Comment by b-** [comment]
I didn't test this, but I don't think it will work as-is. 

The `macfand.service.gen` is actually a shell script that spits out a systemd service. See [this line in the Makefile](https://github.com/ablakely/macfand/blob/master/Makefile#L48) (and the commented out one above it).

Maybe that was too clever for its own good, but either way you'll want to template that file based on the install prefix.

**Comment by b-** [comment]
Probably the least-invasive way to fix the PKGBUILD would be to add a [`.install` file](https://wiki.archlinux.org/title/PKGBUILD#install) that templates out the right file.

**Comment by CompileMyLife** [comment]
When you say template, what does that mean exactly. I do understand now that it was too clever of a fix. From actually rereading the Makefile and the context now of `macfand.service.gen`. When you say "...templates out the right file." What does that mean?

**Comment by b-** [comment]
> When you say template, what does that mean exactly. I do understand now that it was too clever of a fix. From actually rereading the Makefile and the context now of `macfand.service.gen`. When you say "...templates out the right file." What does that mean?

What I meant is that `macfand.service.gen` is a shell script that generates the service file based on what the variable `PREFIX` is set to. I submitted a PR on your fork with what I _think_ should fix this.

(I take back what I said about a `.install` script, I guess we can just put it into the PKGBUILD since we're kind of already running a perl script as sudo!)

**Comment by CompileMyLife** [comment]
The make build-install phases:
macfand-git_PKGBUILD_fix

macfand can be seen among the processes in top:
macfand-git_top

So I think this does work!

**Pull request closed without merging**
